esphome:
  name: vintageradio
  friendly_name: Vintage Radio
  on_boot:
    then:
      - switch.turn_off: use_wake_word
      - light.turn_on:
          id: ledrings
          effect: Waiting
          brightness: 20%


esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Mictest Fallback Hotspot"
  #   password: "ndzHUU5vBjfX"

# captive_portal:
  
esp32_touch:

wled:

number:
  - platform: template
    name: LED Brightness
    id: ledbrightness
    min_value: 0
    max_value: 1
    step: .01
    optimistic: true
    initial_value: .20

light:
  - platform: status_led
    name: "Status"
    id: stat_led
    pin: GPIO2

  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO4
    rmt_channel: 0
    num_leds: 93
    rgb_order: GRB
    name: "LED Rings"
    id: ledrings
    default_transition_length: 500ms
    effects:
      - wled:
      - pulse:
          name: Custom Pulse
          min_brightness: 0%
          max_brightness: 20%
      - addressable_rainbow:
      - addressable_flicker:
      - addressable_color_wipe:
      - addressable_scan:
          move_interval: 5ms
      - addressable_lambda:
          name: "Wipe In"
          update_interval: 8ms
          lambda: |-
            static int x = 0;
            if (initial_run) {
              x = 0;
              it.all() = ESPColor::BLACK;
            }
            if (x < it.size()) {
              it[x] = current_color;
              x += 1;
            }
      - automation:
          name: Waiting
          sequence:
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 92
                range_to: 92
                red: 100%
                blue: 0%
                green: 0%
            - delay: 500ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - delay: 500ms
      - automation:
          name: Connected
          sequence:
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 92
                range_to: 92
                red: 0%
                blue: 0%
                green: 100%
            - delay: 50ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 84
                range_to: 91
                red: 0%
                blue: 0%
                green: 100%
            - delay: 50ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 72
                range_to: 83
                red: 0%
                blue: 0%
                green: 100%
            - delay: 50ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 56
                range_to: 71
                red: 0%
                blue: 0%
                green: 100%
            - delay: 50ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 32
                range_to: 55
                red: 0%
                blue: 0%
                green: 100%
            - delay: 50ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 0
                range_to: 31
                red: 0%
                blue: 0%
                green: 100%
            - delay: 250ms

      - automation:
          name: Listening
          sequence:
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                range_from: 0
                range_to: 31
                id: ledrings
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 32
                range_to: 55
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 56
                range_to: 71
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 72
                range_to: 83
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 84
                range_to: 91
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            - light.addressable_set:
                id: ledrings
                red: 0%
                blue: 0%
                green: 0%
            - light.addressable_set:
                id: ledrings
                range_from: 92
                range_to: 92
                red: 100%
                blue: 100%
                green: 0%
            - delay: 100ms
            
             
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO15   #TDO on esp32 mini - WS on INMP441
    i2s_bclk_pin: GPIO14    #TMS on esp32 mini - SCK on INMP441
  - id: i2s_out
    i2s_lrclk_pin: GPIO13
    i2s_bclk_pin: GPIO19
    
microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO23    #SO on INMP441
    id: mic_1
    i2s_audio_id: i2s_in
    pdm: false
    adc_type: external

speaker:
  - platform: i2s_audio
    #name: "vintage Radio"
    id: spk_1
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: stereo
    i2s_audio_id: i2s_out

voice_assistant:
  id: va
  microphone: mic_1
  speaker: spk_1

  on_wake_word_detected: 
    - light.turn_on:
        id: ledrings
        effect: Color Wipe
        brightness: 20%

  on_client_connected:
    - light.turn_on:
        id: ledrings
        effect: Scan
        brightness: !lambda |-
          return id(ledbrightness).state;
        red: 0%
        blue: 0%
        green: 100%
    - delay: 2.33s
    - light.turn_on:
        id: ledrings
        effect: Connected
        brightness: !lambda |-
          return id(ledbrightness).state;
    - delay: 500ms
    - light.turn_off: ledrings

  # on_start:
  #   - light.turn_on:
  #       id: ledrings
  #       effect: Wipe In
  #       brightness: 30%

  on_listening:
    - light.turn_on:
        id: ledrings
        effect: Listening
        brightness: !lambda |-
          return id(ledbrightness).state;

  on_stt_end:
    - light.turn_on:
        id: ledrings
        effect: Rainbow
        brightness: !lambda |-
          return id(ledbrightness).state;

  # on_stt_vad_start:
  #   - light.turn_on:
  #       id: ledringsledrings
  #       effect: Rainbow
  #       brightness: 15%

  on_tts_start:
    - light.turn_on:
        id: ledrings
        effect: Rainbow
        brightness: !lambda |-
          return id(ledbrightness).state;

  on_tts_end:
    - delay: 3s
    - light.turn_off: ledrings

  on_end:
    - delay: 3s
    - light.turn_off: ledrings

  on_error:
    - light.turn_on:
        id: ledrings
        brightness: !lambda |-
          return id(ledbrightness).state;
        effect: Addressable Flicker
    - delay: 3s
    - light.turn_off: ledrings

  on_client_disconnected:
    - light.turn_on:
        id: ledrings
        brightness: !lambda |-
          return id(ledbrightness).state;
        effect: Waiting

binary_sensor:
# Rear button
  - platform: gpio
    pin: 
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Rear Button"
    filters:
      - delayed_on: 10ms
    on_click:
    - min_length: 10ms
      max_length: 400ms
      then:
        - light.toggle: ledrings
    - min_length: 3s
      max_length: 5s
      then:
        - button.press: reboot_button

# Rotary Encoder 1 Button
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Rotary 1 Button"
    on_press:
      - switch.toggle: use_wake_word

# Rotary Encoder 2 Button
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Rotary 2 Button"
    on_press:
      - switch.toggle: use_wled

 # Touch pad on top     
  - platform: esp32_touch
    name: "Touch Pad"
    pin: GPIO12
    threshold: 800
    on_press:
      - voice_assistant.start:
         # silence_detection: false
    # on_release:
    #   - voice_assistant.stop:

# Rotary Encoder 1 (Large dial)
sensor:
  - platform: rotary_encoder
    name: "Rotary 1"
    internal: true
    min_value: 0
    max_value: 90
    pin_a: 
      number: 34
      mode:
        input: true
    pin_b: 
      number: 35
      mode:
        input: true
    resolution: 1
    # on_clockwise:
    #   - homeassistant.service:
    #       service: media_player.volume_set
    #       data_template:
    #         entity_id: media_player.vintage_radio
    #         volume_level: "{{ state_attr('media_player.vintage_radio', 'volume_level') + 0.1 }}"
    # on_anticlockwise:
    #   - homeassistant.service:
    #       service: media_player.volume_set
    #       data_template:
    #         entity_id: media_player.vintage_radio
    #         volume_level: "{{ state_attr('media_player.vintage_radio', 'volume_level') - 0.1 }}"

# Rotary Encoder 2 (Small dial)
  - platform: rotary_encoder
    name: "Rotary 2"
    id: led_brightness
    internal: true
    pin_a: 
      number: 21
      mode:
        input: true
    pin_b: 
      number: 18
      mode:
        input: true
    resolution: 4
    min_value: 0
    max_value: 100
    filters:
      - or:
        - debounce: 0.1s
        - delta: 10
    on_value:
      then:
        - number.set:
            id: ledbrightness
            value: !lambda |-
              return id(led_brightness).state / 100;


switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);

  - platform: template
    name: Use WLED
    id: use_wled
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      - light.turn_on:
          id: ledrings
          effect: wled
          brightness: !lambda |-
            return id(ledbrightness).state;
    turn_off_action:
      - light.turn_on:
          id: ledrings
          effect: none
          brightness: !lambda |-
            return id(ledbrightness).state;
      - delay: 1s
      - light.turn_off: ledrings

button:
  - platform: restart
    id: reboot_button
    name: "Restart"
